### ISSUE TITLE
Problem with Frame style "Headers, top and bottom" on v1.1.0 in TB for MAC

### ISSUE THREAD

**Issue by bmscmoreira** [dreadnaut/bordercolors-d#1]
Frame style "Headers, top and bottom" on v1.1.0 in TB for macOS seems not to be working, as no borders are displayed. Tested with the same version in TB for Windows and it works.
Both TB versions are 60.3.1.

**Comment by revad** [comment]
Frame style "Headers, top and bottom" does not work on Linux either. Neither does "Headers"
TB v60.5.0. Bordercolors D v1.1.1 SuSE Linux
And indeed it does work on Windows 10 - same versions.
Strange.

**Comment by dreadnaut** [comment]
I don't have a Mac to test on, but I can definitely check on Linux. It's likely that the default styles vary depending on the platform, and our overrides only cover the Windows styles.

**Comment by dreadnaut** [comment]
I think I have fixed the issue on Linux, and I have uploaded a new version here on GitHub:
https://github.com/dreadnaut/bordercolors-d/releases/tag/v1.1.2

@bmscmoreira Could you check if the fix also works for MacOS?

**Comment by revad** [comment]
wfm on Linux

**Comment by bmscmoreira** [comment]
Thanks, working on macOS! (only bottom bar is slightly thinner than the others and not completely aligned with the bottom of the header, but not a problem for me)

![2019-04-06_08-59-16_PM](https://user-images.githubusercontent.com/3017910/55674643-313b4600-58af-11e9-9e00-960179a4d67f.jpg)

**Comment by dreadnaut** [comment]
With the rewrite for TB78, this style cannot be rendered anymore, so I'll close this issue 🙁

If none of the styles in the new version is good enough, [let me know](https://github.com/dreadnaut/bordercolors-d/issues/10)!
