### ISSUE TITLE
Cannot set colour on Linux from colour wheel

### ISSUE THREAD

**Issue by revad** [dreadnaut/bordercolors-d#12]
TB 78.2.2 (64-bit) on SuSE Linux - xfce
Addon version 2020.9.1 (downloaded from here)

Setting the colour by clicking the colour wheel does not work.
Using the colour-picker does. So not serious - maybe only Linux.

See video:
https://github.com/revad/revad.github.io/blob/master/shared/screenrecorder-bordercolors-2020-09-20.mp4

Do the prefs have to be accessed from the 3-dot menu, btw? I thought they were missing at first.
On my addon 'Limit non-BCC recipients) they appear as a tab. 

Your manifest:
    "options_ui": {
      "browser_style": true,
      "open_in_tab": true,
      "page": "pages/options.html"
    },

Mine:
 "options_ui": {
    "page": "prefs.html",
    "browser_style" : true,
    "chrome_style": true
  },

**Comment by dreadnaut** [comment]
I can't double check now—no Linux at hand—but from the video it looks like the color does not actually change when you move the wheel: the RGB/HSL values in the dialog are updated, but not the hexadecimal "Color name". So when you click on "Select", the same color is applied.

Could you check if the value updates correctly in this [online demo](https://html5tutorial.info/html5-color.php)?

Regarding the options, they are currently in a separate tab because if I try to inline them I get this cryptic error
```
TypeError: prin.URI is null — ConduitsParent.jsm:123:58
```
so I left it for later to investigate 🙂

**Comment by revad** [comment]
It seems to depend on the initial value. The online demo works - from its red starting point. On the colour picker the little circle is at a corner of the triangle, on the inner edge of the outer ring.
On your addon the initial circle is on the edge of the triangle but not at a corner. Clicking on the outer ring, as I did in the video, does not change the hex colour name, as you saw on the recording. But if I click first elsewhere within the triangle, the colour name does change, and then I can click on the outer ring. 
In the online demo, if I manually enter all the initial values from your addon, it misbehaves like the addon. So it appears to be a bug in the widget.
I've played with this for quite a while, but not discovered what value, or combination of values, triggers this effect. And I don't know whether this widget is common to other Linux distros.

On the options tab, I'll see if get the the error you get.

**Comment by revad** [comment]
Options tab:
https://bugzilla.mozilla.org/show_bug.cgi?id=1641577
The workround in comment 16 appears to work.

**Comment by revad** [comment]
Colour picker: I suspect this is a bug in the mozilla gtk widget.
Bug 1489028 is similar - not what we see here - but it's classified as "product:core component:widget:Gtk"
Listing all such bugs I don't see this one.
Perhaps easier to use a colour that doesn't trigger the bug, when you have a Linux system to experiment on.

**Comment by dreadnaut** [comment]
Hello there! I made a small change to the fallback color, from a neutral gray to one that should be just off the side. If you have time, could you test the [new release](https://github.com/dreadnaut/bordercolors-d/releases/tag/v2020.10.1)?

**Comment by revad** [comment]
Well, it's different. I wrote before "Clicking on the outer ring, as I did in the video, does not change the hex colour name".  It does now, so I think it's working OK.

It's not obvious how the gtk colour wheel gizmo is supposed to work. If I want bright green, say, I would expect to just hit that colour on the outer ring and see that reflected in the sample box. But that doesn't have any noticeable effect. You have to move the circle on the inner triangle too to make it more saturated. And to be fair, the tooltip does say exactly that.

Anyway, I think it's probably working as intended, and it's good enough. Most people, like me, will click away until they see a colour they're happy with.

(Took me a while to remember where the prefs were hiding btw.)

**Comment by dreadnaut** [comment]
Thanks for testing it! Although not perfect, I don't think there is much else I can do for the moment. I'll close this as fixed.

Regarding the options, I hear you! There's a [new release](https://github.com/dreadnaut/bordercolors-d/releases/tag/v2020.10.2) which moves the options in the Add-on tab, but also updates the any open compose windows when you change any settings. With that in place, trying different styles or colors is much easier 🙂

Thanks for finding the options workaround!
