### ISSUE TITLE
Switching style in one editor changes the style in other open editor windows as well

### ISSUE THREAD

**Issue by speedball2001** [dreadnaut/bordercolors-d#13]
When I have more than one editor window open, switching the identity in one editor changes the style in all open editor windows.

Steps to reproduce:

1. Have more than one identity configured in Thunderbird with different colors

2. Open two editor windows

3. Choose different identity in editor 1

Expected behavior:

* The style should change only in the editor where the identity was changed.

Actual behavior:

* Style changed in editor 1 and editor 2

**Comment by dreadnaut** [comment]
Whops, that was a big one! I did not think about testing with multiple windows 🤦‍♂️

There's a [new release](https://github.com/dreadnaut/bordercolors-d/releases/tag/v2020.10.1) that should fix the problem, could you give it a try?

**Comment by speedball2001** [comment]
Yes, this version works as expected. Thank you for fixing the bug so quickly.

**Comment by dreadnaut** [comment]
Thanks for testing it! I'll submit it to the [add-ons directory](https://addons.thunderbird.net/en-GB/thunderbird/addon/bordercolors-d/), and hopefully it'll be approved in a few days.
