### ISSUE TITLE
Styles do not apply when a color override is in place

### ISSUE THREAD

**Issue by Foxfan100** [dreadnaut/bordercolors-d#14]
I have several email accounts, and have allocated each with a different colour via the Bordercolors options menu in its Add-ons entry. The border position selected is top and bottom border. 

However, when I compose an email from any one of my accounts, the border remains the same colour, at a dark blue, although it is in the correct position. More notably, the colour it shows is not anywhere near the colours I have allocated per email account.

Examples are attached.

I note that you mention elsewhere that there are some bugs needing resolution, but it is not clear whether this particular colour problem is among them.

![bordercolor#1](https://user-images.githubusercontent.com/22635836/97800129-b1ac5f00-1c2a-11eb-9552-11cc8973436f.jpg)
![border#2](https://user-images.githubusercontent.com/22635836/97800133-b8d36d00-1c2a-11eb-995f-ec0715ef8077.jpg)

**Comment by dreadnaut** [comment]
That's a new and interesting bug there! Something seems to override the color, are you using any custom theme or CSS?

Or are these two colors the same?
![image](https://user-images.githubusercontent.com/584584/97800683-22ee1100-1c2f-11eb-8745-e01e115fccb7.png)

**Comment by Foxfan100** [comment]
I see what causes it.

In Settings>General>Fonts & Colors>Colors, I had the text and background set up to the blue and buff colours, but with the Override set to "Always". That makes TB always use my colour set and overrides anything else. Changing the "Override" to "Never" immediately allows the BorderColor add-on to show correctly, but it then reverts my colour scheme on non-composing tabs (such as those in TB Settings) to a white background and black text.

However, on Compose tabs, when writing an email, I retain my text and background colours, AND have the specified BorderColors for the email account concerned. That, of course, is what the add-on is supposed to do, so it works fine.

On reading Inbox and other inbound emails, the background and text have reverted to white and black in the cases where there were unfilled areas in an email, which were then shown with my buff/blue colours.

I am using a venerable userchrome.css file in my chrome folder for the purpose of showing vertical and horizontal gridlines of different weights and colours in my mail folder listings, and, had the solution above not presented itself, I planned to disable it to see whether that made any difference. Now there seems to be no need for that.

I hope this is clear! There are some other permutations available in the TB Settings Color section, and I'll try some to see if they produce any different effects, but I don't think they will, in such a way as to affect your add-on.

**Comment by dreadnaut** [comment]
Thanks for investigating! I can reproduce it here as well: setting "Override" to "Always" means that the border or background set by BorderColors are ignored, and the configured colors appear instead.

As far as I can see, I _cannot_ fix this 😢  The override happens at a higher level, so it takes precedence on the add-on styles, even if I mark it as `!important`.

**Comment by Foxfan100** [comment]
I don't think it really needs fixing, as the Add-on is "doing what it says on the tin". For me, it's more important to have the add-on colours working properly than it is to have pretty colours on, for example, the Settings screen. In any case, my colour scheme was more for my liking when composing emails, and, since I can have both the BorderColors and my scheme when I do that, it works fine for me.

**Comment by dreadnaut** [comment]
Great then, glad the add-on is useful to you!
