### ISSUE TITLE
Gradients are stretched and sometimes invisible (with long emails)

### ISSUE THREAD

**Issue by pejotigrek** [dreadnaut/bordercolors-d#15]
if I understand correctly, the height of gradient is derived from the "height of email", meaning: not the message window, but the message body itself. while I don't have any idea for the bottom gradient [and it's sometimes not visible, especially with long emails, and unfortunately I've got a lot of them at work - forward of the forward of the forward ... etc. ;)], is it possible to make the upper-right-corner gradient to stay not resized?
I mean - so it can be the very same size no matter how long the message is. that would be great for visibility. now - it sometimes goes way beyond the lower border of the window, and while I scroll the message, I'm revealing the rest of gradient.

**Comment by dreadnaut** [comment]
Good spot, thank you!

I think I've fixed it by having the background stay in place as the editor is resized or grows in height. Could you try this [pre-release](https://github.com/dreadnaut/bordercolors-d/releases/tag/v2020.11.1)?

**Comment by pejotigrek** [comment]
just tested. works perfect!
both on top-right and bottom gradients. they stay with one size, fixed to background and don't scroll with message body.
thank you for fixing that! :)

**Comment by dreadnaut** [comment]
Great, thanks for testing it!
