### ISSUE TITLE
Update (~9 Nov) has broken text/background colour

### ISSUE THREAD

**Issue by original-birdman** [dreadnaut/bordercolors-d#16]
I use the Dark Theme, but have dark text on a light background set for both reading (General-> language & Appearance -> Colours) and composing (Composition -> HTML Style -> "Use reader's default colours" is UNSET).

The recent update (which includes, "Dark and custom themes support") has broken this, as it just puts the Dark Theme colours into place.

**Comment by dreadnaut** [comment]
Sorry about that! I'll see if I can detect custom colors and use them, instead of overriding your settings. Otherwise, we might need a checkbox to disable the override.

**Comment by dreadnaut** [comment]
Seems like I made things more complicated than necessary last time. I reverted the dark theme changes and used a simpler method that doesn't clash with custom colors.

Could you test this [new version](https://github.com/dreadnaut/bordercolors-d/releases/tag/v2020.11.4) and let me know if it solves your issue?

**Comment by original-birdman** [comment]
Yes. That seems to work fine.

Thanks.

**Comment by dreadnaut** [comment]
Great, thank you!
