### ISSUE TITLE
Colors do not apply, all borders are black

### ISSUE THREAD

**Issue by tschomacker** [dreadnaut/bordercolors-d#17]
Hey guys,
Great Add-On! Became especially viable to me, since [Identity Chooser](https://addons.thunderbird.net/en-US/thunderbird/addon/identity-chooser/) Add-On out source their color functionality to this add-on. As [Bob](https://addons.thunderbird.net/en-US/thunderbird/addon/bordercolors-d/reviews/1164747/)  pointed out it would be great if the add-on would work under Thunberbird 78.5 and higher. The problem for me is that, the borders are all black. I have tried all forms of borders with no change.  I use system colors and I tried both the dark and the light theme.

**Comment by dreadnaut** [comment]
Hello Thorben! BorderColors has about 5000 users on Thunderbird 78.5 and 78.6, so I can guarantee you that it's working with that version... for most people. On the other hand, I would like to investigate why it's not working for you.

Could you give me more details? For example:
- which operating system are you running?
- do colours appear correctly in the add-on option page?
- are you running any other addons that affect the message composer?

Also, could you try this for me?
1. open the Error Console (Tools → Developer tools → Error console)
2. clear the console (button in the top left)
3. open a new compose window

Any error messages at that point? Can you copy the lines here?

**Comment by tschomacker** [comment]
Hello dreadnut,
Thanks for the quick reply! I will try to give as much details as I can: 
- Windows 10 Education 1909
- Thunderbird 78.6

All Installed Plugins:
- Border Colors
- Google Calendar
- Duplicate Message Remover

Error console:
```
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. blank
New compose tab 6 with identity id3 styleswitcher.js:31:15
Applying new style for identity id3 to tab 6 styleswitcher.js:38:13
```
This is how the add on page looks like:
![image](https://user-images.githubusercontent.com/22526154/102820545-b7762380-43d5-11eb-90db-3093253d91dc.png)
This is how the compose window looks like (blue identity):
![image](https://user-images.githubusercontent.com/22526154/102820613-d83e7900-43d5-11eb-9ba1-4d0a2f8e3d1e.png)

**Comment by dreadnaut** [comment]
Seeing this control in black-and-white makes me wonder if you are using a high-contrast settings, either at Windows level or in Thunderbird.
![image](https://user-images.githubusercontent.com/584584/102821699-6fec9900-43cf-11eb-80d9-7bca08cc8316.png)

The default style would be blue:
![image](https://user-images.githubusercontent.com/584584/102821761-88f54a00-43cf-11eb-959f-c99f244844dc.png)

Can you have a look at #16 and see if the solution works for you?

**Comment by dreadnaut** [comment]
Sorry, I meant #14 !

**Comment by tschomacker** [comment]
> Sorry, I meant #14 !

This fixed the issue indeed.
