### ISSUE TITLE
How to deploy with predefined configuration?

### ISSUE THREAD

**Issue by bastien30** [dreadnaut/bordercolors-d#19]
Hello,

First, thanks for this usefull extension !

I'm planning to use it at work for many workstations, and I would like to know if there is a way to automatically configure it ?
I'm using the Mozilla policies's to install the extension, but I don't find any configuration file or similar that i can deploy into all Thunderbird profils.

Is there a way to do what I'm trying to do ?

Thanks !

**Comment by dreadnaut** [comment]
That's a great question, I'm not sure myself. "Mail-extension" add-ons store their data via JavaScript storage, which ends up in a SQLite database in the user's profile, under `storage/default/moz-extension+++...`, where the last directory contains some kind of unique id.

You could copy those files across, but I don't think you can easily guess the directory name. Might be worth bringing this question to the TB dev team, either on [matrix](https://matrix.to/#/#tb-addon-developers:mozilla.org) or the [mailing list](https://thunderbird.topicbox.com/groups/addons).

**Comment by bastien30** [comment]
Hello,

Ok, I thought there was a configuration file somewhere or a thunderbird pref.

I've found the corresponding directory, but it's not working to just copy it to another profile.
The ID in the directory name seems to be different accross profiles.

Beside, all my users does not have the same mail accounts configured and so, I guess deploying a global configuration that works everywhere may be difficult.

So I think I'm giving up my first idea, I'll probably do a How-To guide that I'll send to all users, it will be simpler and easier for me.

Thanks anyway.
