### ISSUE TITLE
smtp error message and duplication of messages

### ISSUE THREAD

**Issue by AndroSteph** [dreadnaut/bordercolors-d#20]
With Thunderbird 78.7.0 configured with 8 different butl addresses and different providers. I have the following problem, smtp + error message in sent and received messages they are visible several times. 2 or 3 times the same message sent or received.
If I disable this add-on, the problem disappears completely and everything works normally.

The error is not only with outlook smtp, but also with other providers.

![2021-02-01_15-25-26](https://user-images.githubusercontent.com/69978916/106647297-07c4d180-658f-11eb-87c2-0609315def7a.png)

**Comment by dreadnaut** [comment]
Wow, that's quite unexpected: the add-on code doesn't go anywhere near SMTP and message lists. Let's try to track it down! 🛠

Can you try this:
- open the error console? (see Tools \ Developer Tools \ Error Console)
- clear any previous messages with the "bin" button in the top left
- compose a new email, and try to send it
- if anything suspicious pops up in the error console, copy-paste it here please!

I'll assume that you are using the latest add-on version, the one that comes from the Thunderbird add-on website.

**Comment by AndroSteph** [comment]
Hello,

Thank you for reading my message and reporting the problem.

I did exactly what I was asked to do. I specify that if I don't activate this add-on I don't get this error message and not the 3 messages in inbox and outbox.

See you soon ;-)

![01](https://user-images.githubusercontent.com/69978916/106866673-08fc1880-66cd-11eb-867f-87c7cd100a25.png)
![02_Outboox](https://user-images.githubusercontent.com/69978916/106866677-0994af00-66cd-11eb-9728-e89f406e96c1.png)
![03_Inbox](https://user-images.githubusercontent.com/69978916/106866678-0a2d4580-66cd-11eb-84f5-8214d5577437.png)
![04_Error_message](https://user-images.githubusercontent.com/69978916/106866679-0a2d4580-66cd-11eb-9c35-94dd9da5c498.png)
[new 1.txt](https://github.com/dreadnaut/bordercolors-d/files/5924278/new.1.txt)

**Comment by AndroSteph** [comment]
Hello,

Thank you for reading my message and reporting the problem.

I did exactly what I was asked to do. I specify that if I don't activate this add-on I don't get this error message and not the 3 messages in inbox and outbox.

See you soon :-)
![01](https://user-images.githubusercontent.com/69978916/106866891-482a6980-66cd-11eb-9538-760ca42965cd.png)
![02_Outboox](https://user-images.githubusercontent.com/69978916/106866895-48c30000-66cd-11eb-8ce4-8be18dfa981d.png)
![03_Inbox](https://user-images.githubusercontent.com/69978916/106866898-495b9680-66cd-11eb-8cd7-1d87e5fa88b1.png)
![04_Error_message](https://user-images.githubusercontent.com/69978916/106866899-495b9680-66cd-11eb-9623-29905b139d32.png)
[new 1.txt](https://github.com/dreadnaut/bordercolors-d/files/5924286/new.1.txt)

**Comment by AndroSteph** [comment]
and ...
[new 2.txt](https://github.com/dreadnaut/bordercolors-d/files/5924292/new.2.txt)

**Comment by AndroSteph** [comment]
![05](https://user-images.githubusercontent.com/69978916/106867706-37c6be80-66ce-11eb-8bd0-6773fad9ef44.png)

**Comment by AndroSteph** [comment]
I remain available for other tests ;-)

**Comment by fran-f** [comment]
Thanks for the logs! I have an idea maybe: do you have any other add-on installed? Could you try disabling all of them *except* BorderColors-D?

**Comment by dreadnaut** [comment]
Thanks for the logs! I have an idea maybe: do you have any other add-on installed? Could you try disabling all of them *except* BorderColors-D?

**Comment by AndroSteph** [comment]
Um, I'm stupid, I didn't even think about a conflict with another add-on.

So I made several tests and EFFECTIVELY the conflict is with my add-on "Antidote" (https://www.druide.com/fr)

So sorry for using your time for nothing.

After my tests and with "Anditode" disabled, I don't have the error message and the tripling of the messages anymore.

Thank you for having the good idea to make me do these tests ...and sorry !

**Comment by dreadnaut** [comment]
No problem at all!

Good luck with debugging, let me know if you need any details about what BorderColors does with the compose window! (spoiler: not much, mainly [adding and removing CSS](https://github.com/dreadnaut/bordercolors-d/blob/master/modules/styleswitcher.js))
