### ISSUE TITLE
TB 91 not sending mail while bordercolors-d is active

### ISSUE THREAD

**Issue by peter-rindfuss** [dreadnaut/bordercolors-d#24]
Hi,
With the new TB 91, I cannot send messages anymore while bordercolors-d is active. Simply nothings happens, and the compose window stays open. Disabling bordercolors-d solves the problem. My precise TB version is 91.0.3.
I like the add-on, and I hope there will be a solution. Peter

**Comment by dreadnaut** [comment]
Hello again Peter,
I have tried to reproduce the issue on the latest Thunderbird version without luck: I can compose and send emails without trouble.

Still, we could dig a bit further and see if we can solve the problem for you. Do you think you could help me with the steps in the message above?

**Comment by peter-rindfuss** [comment]
Hi, 
I already replied by mail, but it looks that it did not reach you. So here it comes:

The problem occurs, reproducibly, with BorderColors being the only add-on.

This is the error log:

```
11:06:35.580 window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. blank
11:06:35.928 Uncaught Exception { name: "NS_ERROR_FAILURE", message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIEditor.getInlineSpellChecker]", result: 2147500037, filename: "chrome://messenger/content/messengercompose/MsgComposeCommands.js", lineNumber: 401, columnNumber: 0, data: null, stack: "updateEditableFields@chrome://messenger/content/messengercompose/MsgComposeCommands.js:401:38\nComposeFieldsReady@chrome://messenger/content/messengercompose/MsgComposeCommands.js:2739:23\nNotifyComposeFieldsReady@chrome://messenger/content/messengercompose/MsgComposeCommands.js:461:5\nInitEditor@chrome://messenger/content/messengercompose/MsgComposeCommands.js:9242:15\nobserve@chrome://messenger/content/messengercompose/MsgComposeCommands.js:3803:9\n", location: XPCWrappedNative_NoHelper }
MsgComposeCommands.js:401
11:06:36.259 New compose tab 7 with identity id1 styleswitcher.js:31:15
11:06:36.271 Applying new border style for identity id1 to tab 7 styleswitcher.js:45:13
11:07:09.483 NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIEditor.getInlineSpellChecker] MsgComposeCommands.js:401
11:07:22.451 Prompter: internal dialogs not available in this context. Falling back to window prompt. Prompter.jsm:1084
```

The "Uncaught Exception" occurs after opening the composer window. The "NS_ERROR_FAILURE" shows up after the sending attempt. When Border Colors is disabled, the "Uncaught Exception" shows up twice, the second occurance replacing the NS_ERROR_FAILURE. 

As this seems to be related to an "InlineSpellChecker", the fact that I use the German version of TB may be relevant.

**Comment by dreadnaut** [comment]
Sorry, the comment by email never appeared 🤷‍♂️

On the other end, I managed to reproduce the issue installing a "Fully localised" version of Thunderbird, in my case I tried with "English (British)" which makes debugging a bit easier for me 😉

I'll have a look in the next days, thank for your help and patience!

**Comment by peter-rindfuss** [comment]
I installed the "German Dictionary", and now I can send.

**Comment by dreadnaut** [comment]
Indeed, I have tried the same here and _after installing a dictionary_ the error is gone.

Odd behaviour. I'll see if there's anything I can do to avoid the issue, but I might file a Thunderbird bug as well.
