### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by enufsed** [dreadnaut/bordercolors-d#25]
I am using Thunderbird version 78.13.0 and the border colors doesn't seem to work. I set it up and restarted but see no changes at all to messages. Am I suppose to do something else to get it to work?

**Comment by dreadnaut** [comment]
Hello there! To get BorderColors to work you would need to:

- Install the add-on
- Select a border style and colors for your identities in the add-on options
- Compose a new message

You can find the add-on options in Thunderbird's "Add-on Manager", under Extensions \ BorderColors D \ Options.

If that is what you have already tried, could it be that you have a *color override* configured in your options? See #14 for more details.

No override, and still not working? Then we'll need some debugging information to investigate further🔍  Follow the steps below to find the add-ons logs.

<details>
  <summary>Where to find error logs</summary>

- Disable all add-ons except BorderColors
- Restart Thunderbird
- Open the error console from Tools \ Developer Tools \ Error Console
- Clear the log with the Bin icon in the top left—we'd like a clean slate
- Open a new compose window, try to send a test email
- If any red text appears in the logs, of any of the messages look suspicious to you, post the contents here—please amend any personal information first
</details>

**Comment by dreadnaut** [comment]
No more information after a few months 🙁  I'll close it.
