### ISSUE TITLE
[Windows:] Options are unreadable (black-on-black)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [dreadnaut/bordercolors-d#26]
Border Colours 2021.4.1
Thunderbird 78.14 x64
Windows 10 Pro - 21H1 (2009: 19043)

When I set Thunderbird's theme to its default theme or to its inbuilt light theme or to its inbuilt dark theme, I see this:

![image](https://user-images.githubusercontent.com/47056543/132923615-ee09c6e6-6632-47d2-aa72-41e04f00b782.png)

I have not tried the addOn on an other operating system.

**Comment by dreadnaut** [comment]
Hello there, that's not a useful options page to see! 🤦

Could you check if you have a *color override* in place in your Thunderbird configuration? See [this comment](https://github.com/dreadnaut/bordercolors-d/issues/14#issuecomment-720074407)

**Comment by LinuxOnTheDesktop** [comment]
Right. Understood. Fixed. Thanks.
