### ISSUE TITLE
Only black color

### ISSUE THREAD

**Issue by abcpop** [dreadnaut/bordercolors-d#28]
I just discover and try "bordercolors-d" extension on TB 91
Despite chosing a different color by account, only BLAK color appears.
For non colored account a pointed black line appears 
Desactivating all other extension does not help
Any way to solve this issue ?
![image](https://user-images.githubusercontent.com/7467332/148900126-8986fb23-383f-4fb1-b6b3-5af29c9fb5d1.png)
![image](https://user-images.githubusercontent.com/7467332/148900179-62b07ff0-cd46-4e89-96f7-eaa99389dac3.png)

**Comment by dreadnaut** [comment]
Hello! That can happen if you have a "color override" set up. See issue
#14.

**Comment by abcpop** [comment]
Thanks 
I could fix it by changing colors in settings:
I chose NEVER "override the colors specified by the content of those selected above" 
![image](https://user-images.githubusercontent.com/7467332/148994150-daa7b85e-c48d-4c76-a25a-096026e7d1d5.png)

**Comment by dreadnaut** [comment]
Great to hear it worked!
