### ISSUE TITLE
Option to include border lines for replies (as opposed to just new mails)

### ISSUE THREAD

**Issue by LewisBHRGWood** [dreadnaut/bordercolors-d#29]
The title says it all. This add on is excellent and just what I needed but I see that whilst the border shows up on new emails, it does not on replies. Perhaps others would find this optional feature useful as well.

**Comment by dreadnaut** [comment]
Oh, that's odd: BorderColors does not make a difference between new and reply compose windows, and as far as I know works fine in both. For example:
![image](https://user-images.githubusercontent.com/584584/154733078-b1d274ff-985f-4363-8bb0-d780918e65b5.png)

Could you give me a few more details on your configuration? Which operating system, Thunderbird version, etc.?

**Comment by dreadnaut** [comment]
No more information after a few months. I'll close this issue, but feel free to re-open it if your problem is still around.
