### ISSUE TITLE
Feature Request: Borders for list pane

### ISSUE THREAD

**Issue by sinkva** [dreadnaut/bordercolors-d#33]
Along with a colorful border around the "New message" window, would it be possible to add a colorful border around the List Pane ? My workflow involves multiple accounts/identities, and sometimes I want to treat similar messages differently, depending on the account/identity. Currently, the List Panes for various accounts/identities look (basically!) identical :-(

**Comment by dreadnaut** [comment]
Hello @sinkva, I suppose you are looking for something like the old [Account Colors](https://addons.thunderbird.net/en-US/thunderbird/addon/account-colors/) add-on? Unfortunately the Thunderbird API does not include a way to style the message list, so we have no way to build something like that.

**Comment by sinkva** [comment]
Well, bummer. 
Yes, the old Account Colors add-on looks like exactly what I was asking for...

**Comment by dreadnaut** [comment]
Sorry about that!

As a workaround, I wonder if a rule that assign a colourful label based on the recipient could help 🤔

**Comment by sinkva** [comment]
A rule that could assign a colorful label based on from/to/cc/subject would be helpful, but -- for my workflow -- only if (like in the old Account Colors add-on) I can avoid "opening" each individual email. That is: It would be helpful if there's some indication right in the list pane, or right in the message pane. So not like the behavior of Bordercolors, which doesn't do its thing until you open a new message (with border colors!) in a new window.

**Comment by fran-f** [comment]
I'm thinking about vanilla Thunderbird rules and tags, not an add-on. The tags you can assign with `1`...`5` and that change the colour of email in the list pane.

![image](https://github.com/dreadnaut/bordercolors-d/assets/50931058/e56dbdd0-eeab-40bc-8f03-3b00a2576df8)
![image](https://github.com/dreadnaut/bordercolors-d/assets/50931058/9b0e1d85-cbc0-4566-9992-1afa25b1ef9a)

**Comment by dreadnaut** [comment]
I'm thinking about vanilla Thunderbird rules and tags, not an add-on. The tags you can assign with `1`...`5` and that change the colour of email in the list pane.

![image](https://github.com/dreadnaut/bordercolors-d/assets/50931058/e56dbdd0-eeab-40bc-8f03-3b00a2576df8)
![image](https://github.com/dreadnaut/bordercolors-d/assets/50931058/9b0e1d85-cbc0-4566-9992-1afa25b1ef9a)

**Comment by sinkva** [comment]
Ah, I get it. Unfortunately, I'm already using tags (and their colors) in my workflow. 

There's no straightforward way to add a background color (or colored borders <grin>) 
either to the list pane or to the message pane, I suppose? 

I'm guessing it would be hard to work around the Thunderbird API... Or is that a feature request we can ask the Thunderbird devs for?

**Comment by dreadnaut** [comment]
No way around it that I know of. And the developer of Account Colors would have probably jumped on it if it existed.

Definitely worth a feature request, it might be that with all the front end improvements going on it's something that Thunderbird could support.
