### ISSUE TITLE
Sporadically doesn't show borders, and disables Send button

### ISSUE THREAD

**Issue by dmusican** [dreadnaut/bordercolors-d#35]
I've been an enthusiastic user of BorderColors D for years, and it's great.

I've started experiencing a problem with Thunderbird 128 (.3? I'm not sure when it started), where when I create a new email message, _sometimes_ Border Colors D doesn't kick in. A new email window appears as usual, but there's no border color shown, and when this problem happens the Send button on the email doesn't respond. It seems to be more likely to happen when I've been doing other tasks on my computer for a while, and then I come back to an open Thunderbird session. I'm using Thunderbird 128.3.1, on Ubuntu 22.04.1

I have tried extensively, and for the life of me I cannot come up with a reliable set of instructions to force this problem to happen. But it happens frequently; it is nearly guaranteed to happen sometime when I'm doing a series of emails, and again, it feels to me like it is tied to something about windowing and returning to Thunderbird, but I can't guarantee that.

If this is useful information, I have the same problem when running the extension Identity Chooser, which I also use. If either one or both of these two extensions are enabled, I have the problem described above where sporadically these extensions (whichever are enabled) don't work, and the Send button on my email doesn't work. I have verified that with all other extensions disabled, enabling either one of these two extensions, by themselves only, will cause this problem. But when both are disabled, the problem in clicking Send is gone.

My best guess, with no real data behind it, is that there's some sort of windowing race condition happening as a result of some recent change that Thunderbird made. But I don't know if that's true or how to diagnose it. I'm happy to provide more additional information if that would be useful.

Thanks for your hard work on this extension, it has saved me many times from sending an email from the wrong identity.

**Comment by fran-f** [comment]
Hello Dave, and thanks for you detailed report.

I know you said "sometimes", but are you able to reproduce this issue with Thunderbird "Error Console" open? BorderColors should output some information there, if all goes well, or we might spot an error message.

You can open the Error Console from the menu bar, under Tools \ Developer Tools \ Error Console
![image](https://github.com/user-attachments/assets/5fc17561-2eee-41df-beda-7f8b0ed9bc93)

When BorderColors can do its job, it outputs lines like these:
```
New compose tab <nnn> with identity <xxx>
Applying new border style for identity <xxx> to tab <nnn>
```

**Comment by dreadnaut** [comment]
Hello Dave, and thanks for you detailed report.

I know you said "sometimes", but are you able to reproduce this issue with Thunderbird "Error Console" open? BorderColors should output some information there, if all goes well, or we might spot an error message.

You can open the Error Console from the menu bar, under Tools \ Developer Tools \ Error Console

![image](https://github.com/user-attachments/assets/39bc70a2-6231-4341-b53b-f3f3ed575398)


When BorderColors can do its job, it outputs lines like these:
```
New compose tab <nnn> with identity <xxx>
Applying new border style for identity <xxx> to tab <nnn>
```

**Comment by dmusican** [comment]
Will do, I'm working on it. The problem has decided to not appear since you posted your message. I'm not superstitious, but erratically behaving computers have a remarkably magical aspect to them.

I'll give it a few days with Error Console running and see what I can come up with. Thanks for the response.

**Comment by dmusican** [comment]
Caught one! I hit reply on a message soon after starting, Border Colors didn't kick in, so then I opened up the Error Console.

Here's what Error Console looks like:

```
1729873504032	addons.xpi	WARN	Checking /snap/thunderbird/532/usr/lib/thunderbird/distribution/extensions for addons
1729873504034	addons.xpi	WARN	Checking /snap/thunderbird/532/usr/lib/thunderbird/distribution/extensions/locale-en-US for addons
1729873505708	addons.xpi	WARN	Addon with ID thunderbird-compact-light@mozilla.org already installed, older version will be disabled
1729873505708	addons.xpi	WARN	Addon with ID thunderbird-compact-dark@mozilla.org already installed, older version will be disabled
Hello there, I'm BorderColors-D! [background.js:11:9](moz-extension://d344d78e-9a75-49b8-b5ae-bd5fbdc743e7/pages/background.js)
NotFoundError: No such JSProcessActor 'BrowserToolboxDevToolsProcess'
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. [msgHdrView.js:4214:7](chrome://messenger/content/msgHdrView.js)
```
​

**Comment by dreadnaut** [comment]
Thank you! As "control" for the experiment, could you try the same again?

- Open Thunderbird
- Reply to a message, hopefully BorderColors will kick in this time
- Open the console and grab the logs

That way we can compare behaviour, and see if that "Layout was forced" is related.

**Comment by dmusican** [comment]
Sure! The first time I replied, BorderColors did not kick in. I've seen this --- it is more likely to fail the first time on startup, but less likely to fail when I'm trying to make it happen. :) Then I immediately tried replying again, and it did kick in. Here are the logs:

```
1729875731839	addons.xpi	WARN	Checking /snap/thunderbird/532/usr/lib/thunderbird/distribution/extensions for addons
1729875731840	addons.xpi	WARN	Checking /snap/thunderbird/532/usr/lib/thunderbird/distribution/extensions/locale-en-US for addons
1729875733359	addons.xpi	WARN	Addon with ID thunderbird-compact-light@mozilla.org already installed, older version will be disabled
1729875733360	addons.xpi	WARN	Addon with ID thunderbird-compact-dark@mozilla.org already installed, older version will be disabled
Hello there, I'm BorderColors-D! [background.js:11:9](moz-extension://d344d78e-9a75-49b8-b5ae-bd5fbdc743e7/pages/background.js)
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. [msgHdrView.js:4214:7](chrome://messenger/content/msgHdrView.js)
New compose tab 2 with identity id2 [styleswitcher.js:31:15](moz-extension://d344d78e-9a75-49b8-b5ae-bd5fbdc743e7/modules/styleswitcher.js)
Applying new border style for identity id2 to tab 2 [styleswitcher.js:45:13](moz-extension://d344d78e-9a75-49b8-b5ae-bd5fbdc743e7/modules/styleswitcher.js)
```

And finally, I then did the experiment one more time. In my testing, BorderColors is more likely to wake up when I open the Error Console first. At least, I think that's the case --- again, it's not quite predicatable on any of this. Anyway, I opened up Error Console, and then I replied. BorderColors did in fact kick in. Here is the log from this attempt:

```
1729875913945	addons.xpi	WARN	Checking /snap/thunderbird/532/usr/lib/thunderbird/distribution/extensions for addons
1729875913946	addons.xpi	WARN	Checking /snap/thunderbird/532/usr/lib/thunderbird/distribution/extensions/locale-en-US for addons
1729875915755	addons.xpi	WARN	Addon with ID thunderbird-compact-light@mozilla.org already installed, older version will be disabled
1729875915755	addons.xpi	WARN	Addon with ID thunderbird-compact-dark@mozilla.org already installed, older version will be disabled
Hello there, I'm BorderColors-D! [background.js:11:9](moz-extension://d344d78e-9a75-49b8-b5ae-bd5fbdc743e7/pages/background.js)
sizeToContent() is deprecated and will be removed in the future. [commonDialog.js:132:10](chrome://global/content/commonDialog.js)
window.controllers/Controllers is deprecated. Do not use it for UA detection. 2 [blank](about:blank?)
New compose tab 1 with identity id1 [styleswitcher.js:31:15](moz-extension://d344d78e-9a75-49b8-b5ae-bd5fbdc743e7/modules/styleswitcher.js)
Applying new border style for identity id1 to tab 1 [styleswitcher.js:45:13](moz-extension://d344d78e-9a75-49b8-b5ae-bd5fbdc743e7/modules/styleswitcher.js)
```

**Comment by dmusican** [comment]
My system upgraded Thunderbird to 128.4.3, and I haven't seen this problem since. Thunderbird must have broken something in the last release that they've fixed. I'm going to optimistically close this bug and hope that all is good; I'll come back if it recurs. Thanks for all of your help!

**Comment by dreadnaut** [comment]
Thank you for the update, Dave!  (Apologies for the slow response otherwise)
