### ISSUE TITLE
Changes for TB68

### ISSUE THREAD

**Issue by revad** [dreadnaut/bordercolors-d#5]
Bordercolors D requires changes to work on TB68 - including to replace the xul colorpicker which was removed in TB64.

I amended it locally to work on TB68a on Linux. I added a new manifest.json and made changes to options.xul and options.js Those 3 files are in the link.

I think the earliest version of TB this will work with is 64 (after bug 1489930 fixed) but I've only tested it on 68a, and only on Linux (bearing in mind #1).

Hope you find this useful and can update the ATN version for when 68 is released.

I've linked 1 file to this:
* bordercolors_d_68_changed_files.zip (2.3 kB) hosted on Dropbox: https://www.dropbox.com/s/7483xl2se8llpps/bordercolors_d_68_changed_files.zip?dl=0
(I'll delete that archive when you have downloaded it.)

Dave

**Comment by dreadnaut** [comment]
Thank you very much Dave, I had no idea of the add-on changes coming up!
I have downloaded the files, I'll prepare a branch for a future version 2.

**Comment by revad** [comment]
My version (plus the style changes from #1) works in 67b but not the latest 68a: prefs don't save. This may be a temporary regression or there may be more pref changes on the way in 68.

**Comment by revad** [comment]
I raised a bug. It this is indeed a regression it would be better fixed while 68 is still alpha.
https://bugzilla.mozilla.org/show_bug.cgi?id=1542752

If it isn't fixed we can lose the OK, cancel buttons and save the prefs like 'Use BCC  Instead C' does

**Comment by revad** [comment]
It was deliberate - mirroring a change in Firefox.

Geoff Lanlow has added that change, and solution to here:
https://thunderbird-webextensions.readthedocs.io/en/latest/how-to/extensions68.html#dialog-events

**Comment by revad** [comment]
I fixed that by removing the ondialogaccept line and adding into the onLoad function:
`   document.addEventListener("dialogaccept", function(event) {
      onAccept();
    });
`

**Comment by dreadnaut** [comment]
Working on this at the moment, I'll upload a TB68-compatible version later today. Thanks for all the pointers :)

**Comment by revad** [comment]
FWIW my modified version still works in 68, but the preferences don't work in 69 (colour picker vanished) or 70 (colour picker reappeared but without the account identifers). I didn't investigate why.

**Comment by dreadnaut** [comment]
Ah, it's going to be a bumpy ride for Thunderbird addons 🤔

I've uploadede [release 1.2.0](https://github.com/dreadnaut/bordercolors-d/releases/tag/v1.2.0) here on GitHub, and I'll submit it to the Add-on website in a moment.

Closing this for now, thanks for the help!
