### ISSUE TITLE
"BorderColors D" will not initially install as a local file

### ISSUE THREAD

**Issue by David263** [dreadnaut/bordercolors-d#6]
"BorderColors D" will not install as a local file (as bordercolors_d-1.2.0-tb.xpi). Error message is something like "cannot verify addon". Trying it a second time installs it successfully. Not everyone will try a second time.

**Comment by dreadnaut** [comment]
Thanks for pointing this out, David.

Did you have any trouble installing it from the [add-on page](https://addons.thunderbird.net/thunderbird/addon/bordercolors-d/)?

I'll have a look and see if I can reproduce it. However, installing it from the add-on repository remains the preferred method.

**Comment by David263** [comment]
No, I had no other trouble. But the truth is that I've stopped using it, as the Identity Chooser addon produces somewhat better and more noticeable color effects for my purposes, as well as other useful features. Thanks.

**Comment by dreadnaut** [comment]
[Identity Chooser](https://addons.thunderbird.net/en-US/thunderbird/addon/identity-chooser/) has an option to highlight the whole header, which looks quite nice indeed!

I might add that to BorderColors one day 😛

**Comment by dreadnaut** [comment]
The new mailextension version seems to install fine, so I'll close this.
