### ISSUE TITLE
Mail extension version

### ISSUE THREAD

**Issue by revad** [dreadnaut/bordercolors-d#8]
I thought I'd push for some APIs to enable an MX version of this. See:
https://thunderbird.topicbox.com/groups/addons/T0ab9415ec873c186/bordercolors-addon-as-a-mx

**Comment by dreadnaut** [comment]
Thank you for starting that discussion! I knew about more work would be required for TB78, but I had lost track of the release date—it's coming in June!

I'll download the current beta and what can be done at the moment. As you mentioned on that thread, we need a way to inject CSS in the composer window. Even the content area would be enough, although it would reduce the number of styles available.

**Comment by revad** [comment]
From Philipp's post on the topicbox thread it looks to me as if this is not going to be possible in a pure mail extension before TB78. I could be wrong - Geoff Lankow might suddenly release something.

I don't know, but I think that the mail compose window is still mainly XUL, so TB cannot have content scripts and 'content CSS' like Firefox can. Maybe in future it will me made into a tab, like addons, prefs, etc. I suspect that's why the TB MX APIs refer to the compose window with a tab ID - for future compatibility.

Philipp's idea of using the background colour of the html message is worth exploring - I'll have a look at that. It won't work for plain text emails though. And I don't know how extensive css support is in TB. Gradients? Animation? 

So I think the only way to replicate the bordercolors functionality will be to use an web experiment. If you want to try that I suggest you look at this:
https://github.com/revad/limit_non-BCC_recipients/releases/tag/0.2.0
That was the web experiment version of my replacement for Use BCC Instead C. It detects new compose windows and then counts recipients - where you would want to change the colours. It also has a method of getting preferences and l10n strings into the experiment code - which you'd need too.

**Comment by revad** [comment]
setComposeDetails cannot yet change the message, so cannot add background colours:
https://thunderbird-webextensions.readthedocs.io/en/latest/compose.html#setcomposedetails-tabid-details

**Comment by dreadnaut** [comment]
Work on this is advancing: I have a test version that swtiches styles correctly, but I have not found a way to apply the correct color when the compose window first opens yet.

**Comment by speedball2001** [comment]
Have you tried listening for newly opened windows using browser.windows.onCreated? Something like this might work:

```
browser.windows.onCreated.addListener(function(window) {
  console.log(window);

  if (window.type == "messageCompose") {

    browser.tabs.query({windowId:window.id})
    .then (details => {
      console.log(details);

      browser.compose.getComposeDetails(details[0].id)
      .then(tabdetails => {
        console.log(tabdetails.identityId);

       // set border color according to tabdetails.identityId
      });
    });
}

```

**Comment by dreadnaut** [comment]
Oh, `tabs.query` is exactly what I needed, but I was trying some roundabout way listening to tab creation 🤦‍♀️ Thank you so much, that unblocks me.

At this point I have a basic version that applies a border with a random color, and I'm working on migrating existing configuration. What is left:
- provide a new set of styles, since some of the old ones are not possible anymore (possibly dropping the "width" option)
- convert the preferences dialog
- localisations, later

Work in progress branch
https://github.com/dreadnaut/bordercolors-d/tree/mailextension

**Comment by speedball2001** [comment]
Fantastic. I'm glad I could be of help.

I am the developer of Identity Chooser. I'll probably wont port the coloring part of my addon and instead refer to Bordercolors. Doesn't make much sense to duplicate the functionality.

**Comment by dreadnaut** [comment]
Migrating colors is done, and there's a basic style in place. Next up (probably next week), preferences!

**Comment by speedball2001** [comment]
Did you make progress on this? If I can help, let me know.

**Comment by fran-f** [comment]
Hey @speedball2001 , thanks for prodding me! I got most of the extension working today, with a single style.

I still have the issue we discussed earlier, as the code you suggested also stopped working in the most recent beta. When the "window created" event is triggered, there is not editor in place, so `getComposeDetails` fails. So we are back to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1653698).

In the meanwhile, I'll push my changes on the development branch.

**Comment by dreadnaut** [comment]
Hey @speedball2001 , thanks for prodding me! I got most of the extension working today, with a single style.

I still have the issue we discussed earlier, as the code you suggested also stopped working in the most recent beta. When the "window created" event is triggered, there is not editor in place, so getComposeDetails fails. So we are back to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1653698).

In the meanwhile, I'll push my changes on the development branch.

**Comment by dreadnaut** [comment]
For the moment, I've wrapped the problematic code in a `setTimeout`.

I sent a new version to addons.thunderbird.net, it'll appear in the next days.

**Comment by dreadnaut** [comment]
I have submitted [a new version](https://github.com/dreadnaut/bordercolors-d/releases/tag/2020.9.1) with style selection 🎉

With this, we have a working version that should be OK for daily use, and I'll close this issue. There's more work to be done though, including bringing back localisation.

Thanks to everyone for your support and patience 🙂
